"""Render a CheckResult as a REPORT.md-style markdown document or JSON.

Per CHK-R10 the Proven (mechanical) and Judged (criterion execution) sections
are walled off — never blended. Per CHK-I1 every finding carries a pointer.
Per D3 gaps read as designer questions.
"""

from __future__ import annotations

import datetime
import json

from .checker import CheckResult
from .model import Severity

_PROVEN_KINDS = [
    "conflict",
    "dead_rule",
    "unknown_term",
    "duplicate_definition",
]
_WARNING_STRUCTURAL = [
    "nonconforming_card",
    "stale_decision_ref",
    "orphan_spec",
    "entities_underspecified",
    "frame_strengthened",
]


def _by_kind(result: CheckResult, kind: str):
    return [f for f in result.findings if f.kind == kind]


def render_json(result: CheckResult) -> str:
    counts: dict[str, int] = {}
    for f in result.findings:
        counts[f.kind] = counts.get(f.kind, 0) + 1
    payload = {
        "findings": [f.to_dict() for f in result.findings],
        "counts": counts,
        "exit_code": exit_code(result),
        "specs": [s.name for s in result.specs],
    }
    return json.dumps(payload, indent=2)


def exit_code(result: CheckResult, strict: bool = False) -> int:
    for f in result.findings:
        if f.severity == Severity.ERROR:
            return 1
        if strict and f.severity == Severity.WARNING:
            return 1
    return 0


def _finding_block(f) -> str:
    lines = [f"- **{f.kind}** — {f.message}"]
    if f.witness:
        lines.append(f"  - witness: `{f.witness}`")
    elif f.location:
        lines.append(f"  - location: {f.location}")
    return "\n".join(lines)


def render_markdown(result: CheckResult, strict: bool = False) -> str:
    today = datetime.date.today().isoformat()
    out: list[str] = []
    out.append(f"# Check report — {today} (spec-check, tool-generated)")
    out.append("")
    out.append(
        "Generated by `spec check`. This replaces the hand-run REPORT.md. "
        "Per CHK-R2 / D3 gaps are designer questions; per CHK-I1 every finding "
        "carries a witness or location; per CHK-R10 Proven and Judged are "
        "walled off; per CHK-R7 this run created/modified/deleted no spec file."
    )
    out.append("")

    # entity snapshot (machine-readable baseline for CHK-R11 / D15)
    out.append("<!-- spec-check:entities")
    for ent in sorted(result.entity_vars):
        out.append(f"{ent}: {', '.join(sorted(result.entity_vars[ent]))}")
    out.append("-->")
    out.append("")

    # header transparency notes
    out.append("## Run scope and bounds")
    out.append("")
    out.append(
        f"Specs analyzed ({len(result.specs)}): "
        + ", ".join(s.name for s in result.specs)
        + "."
    )
    if result.baseline_note:
        out.append("")
        out.append(f"Baseline (CHK-R11 / D15): {result.baseline_note}")
    out.append("")
    out.append(
        "Gap detection runs over a **per-spec relevant projection** (CHK-R2): "
        "for each spec, the product of the variables its own requirement guards "
        "constrain. The full cross-spec vocabulary product is not enumerated "
        "(it explodes and asks nothing useful). Bounded coverage, stated loudly:"
    )
    out.append("")
    if result.projection_notes:
        out.extend(result.projection_notes)
    else:
        out.append("- (no requirement guards to project over)")
    out.append("")
    if result.excluded_cards:
        out.append(
            "Cards excluded from semantic analysis (nonconforming under v1 "
            "grammar): "
            + ", ".join(
                f"{cid} ({spec})" for spec, cid in result.excluded_cards
            )
            + "."
        )
        out.append("")

    # ---- Proven ----
    out.append("## Proven (mechanical findings)")
    out.append("")
    for kind in _PROVEN_KINDS:
        fs = _by_kind(result, kind)
        label = kind.replace("_", " ").title()
        if fs:
            out.append(f"**{label}:** {len(fs)} found.")
            out.append("")
            for f in fs:
                out.append(_finding_block(f))
            out.append("")
        else:
            out.append(f"**{label}:** none found.")
            out.append("")

    # ---- Gaps ----
    out.append("## Gaps (designer questions)")
    out.append("")
    gaps = _by_kind(result, "gap")
    if gaps:
        for f in gaps:
            out.append(_finding_block(f))
        out.append("")
    else:
        out.append("None found.")
        out.append("")

    # ---- Structural warnings ----
    out.append("## Structural warnings")
    out.append("")
    any_struct = False
    for kind in _WARNING_STRUCTURAL:
        fs = _by_kind(result, kind)
        if fs:
            any_struct = True
            label = kind.replace("_", " ").title()
            out.append(f"**{label}:** {len(fs)}.")
            out.append("")
            for f in fs:
                out.append(_finding_block(f))
            out.append("")
    if not any_struct:
        out.append("None found.")
        out.append("")

    # ---- Judged ----
    out.append("## Judged (criterion execution status)")
    out.append("")
    if result.criteria:
        out.append(
            f"{len(result.criteria)} criterion card(s) found. No execution "
            "data — review-time execution is out of scope for `spec check`."
        )
        out.append("")
        for c in result.criteria:
            out.append(f"- {c.card_id} ({c.spec}): {c.title}")
        out.append("")
    else:
        out.append(
            "No criterion cards found. No execution data — review-time "
            "execution is out of scope for `spec check`."
        )
        out.append("")

    # ---- Summary ----
    code = exit_code(result, strict)
    errors = sum(1 for f in result.findings if f.severity == Severity.ERROR)
    warnings = sum(
        1 for f in result.findings if f.severity == Severity.WARNING
    )
    out.append("## Summary")
    out.append("")
    out.append(
        f"{errors} error(s), {warnings} warning(s). Exit code: {code}"
        + (" (--strict: warnings promoted to errors)." if strict else ".")
    )
    out.append("")
    return "\n".join(out)
